trigger:
- main

pool:
  name: terraagent

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/basic code'
    backendServiceArm: 'terraconection'
    backendAzureRmResourceGroupName: 'tfdhruvrg'
    backendAzureRmStorageAccountName: 'tfdhruvstg'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terrapip.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/basic code'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/basic code'
    environmentServiceNameAzureRM: 'terraconection'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/basic code'
    environmentServiceNameAzureRM: 'terraconection'